.default_rules:
  rules:

build-job:
  stage: .pre
  script:
    - npm ci
    - npm run build --if-present

test-job:
  stage: test
  script:
    - npm test

docker-job:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/root/theme-builder/theme-builder:latest .
    - docker push $CI_REGISTRY/root/theme-builder/theme-builder:latest
