.default_rules:
  rules:

build-job:
  stage: build
  script:
    - npm ci
    - npm run build --if-present

test-job:
  stage: test
  script:
    - npm test

docker-job:
  stage: docker
  script:
    - docker build .